### ISSUE TITLE
Rendering emojis in Jekyll's feed

### ISSUE THREAD

**Issue by amyspark** [jekyll/jemoji#109]
Hi all,

I'm using this gem along `jekyll-feed`. Since `jemoji` runs at a later stage than the RSS feed generation, it's impossible to have emojis in the feed.

Is it possible to fix this?

**Comment by ashmaroli** [comment]
As of the latest release, it is not possible because the plugin specifically target files that output to `.html` extension:
https://github.com/jekyll/jemoji/blob/0b19f372c5f83c81c9771fdc8ef7c0ebfafc1158/lib/jemoji.rb#L65-L68
