### ISSUE TITLE
Jemojis Appear Large with Sleek Theme

### ISSUE THREAD

**Issue by johnlarkin1** [jekyll/jemoji#119]
I think this might be a previously seen issue, but I'm not exactly sure about the fix. I'm using a fork of `sleek` as my theme and just installed `jemoji`, and the emojis are coming along huge. 
<img width="807" alt="Screen Shot 2022-03-27 at 1 05 17 PM" src="https://user-images.githubusercontent.com/18692931/160294616-f9fbc9f9-1c07-4209-b58c-5f00fe608bb0.png">
<img width="189" alt="Screen Shot 2022-03-27 at 1 05 21 PM" src="https://user-images.githubusercontent.com/18692931/160294619-381c4a93-51df-4bb4-bbc8-f4f878f5d3d9.png">

Does anyone know why this would be happening and what I can do to fix that problem?

To be clear, it looks similar to this:
https://meta.discourse.org/t/emoji-are-huge-when-embedding/32634

I didn't do much in terms of extra editing, but I'm guessing it might be some interaction with how the outside `div` is affecting the inner `emoji`?

**Comment by ashmaroli** [comment]
If you look at the HTML in the screenshot above, you'll see `height="20" width="20"`.
So the issue lies within your theme / CSS styles that is blowing up the emojis.
Hence closing..
