### ISSUE TITLE
emoji shouldn't be compiled in code block

### ISSUE THREAD

**Issue by jingweno** [jekyll/jemoji#12]
I'm trying to show the emoji raw code in GitHub pages like this: `:metal:`, but jekyll renders it as raw image tag. For example, the result of

```markdown
:metal:
`:metal:`
```
is

![screen shot 2014-07-30 at 7 06 20 pm](https://cloud.githubusercontent.com/assets/169064/3759119/6b58547e-1857-11e4-9b60-f2fc11bd7409.png)

Other places like GitHub issues or wikis works as expected but not GitHub pages.

**Comment by kvz** [comment]
Running into this now as well:

![](https://dl.dropboxusercontent.com/s/myk4cac1xk0rrf5/2015-10-01%20at%2010.29%202x.png?dl=0)

Not sure if you suggest I can fix via upgrading?
