### ISSUE TITLE
Support Jekyll 3.0

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jemoji#17]
Much like [as was done for redirect-from](https://github.com/jekyll/jekyll-redirect-from/commit/5206397c8ca37dc10d87462f04996120f2230e1f), we need to relax the matcher.

**Comment by parkr** [comment]
This definitely needs to be updated to be a converter or to be a hook, based on some issues here and with jekyll-mentions. Thoughts? /cc https://github.com/jekyll/jekyll/pull/3553 if we go to the hook route

**Comment by parkr** [comment]
closed by #19.

**Comment by parkr** [comment]
Released in v0.5.0 https://github.com/jekyll/jemoji/releases/tag/v0.5.0
