### ISSUE TITLE
Support the ability to host ones own emojis.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jemoji#21]
This gem is useful, very useful but it would be more useful if we could host our own emoji's.

**Comment by envygeeks** [comment]
Sorry, I need to elaborate, by that I mean you put the emojis in a folder for us, not add our own src.

**Comment by BlockWorld** [comment]
I was just about to post this! +1

**Comment by parkr** [comment]
@envygeeks Are you looking for a CLI command or something? If you wanted to do this, you could copy [the images from gemoji](https://github.com/github/gemoji/tree/master/images/emoji/unicode) to your site and set `emoji.src` to wherever you copied them. I think there are copyright concerns with this so I'd be hesitant to make this easier.

**Comment by envygeeks** [comment]
@parkr That's about what I wanted if I remember right, it's been so long I can only generalize what I wanted since I don't fully remember but copying the emoji's and being able to set where they are is good enough for my case.

**Comment by parkr** [comment]
@envygeeks Ok. I don't think we can get around the copyrights issue of wholesale copying these emoji so I don't think we'll be able to make this easier than a manual copy/paste of that folder at your own discretion. :/ Sorry!
