### ISSUE TITLE
jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jemoji (LoadError)

### ISSUE THREAD

**Issue by dsernst** [jekyll/jemoji#22]
TravisCI is throwing this error when it tries to `jekyll build`.

```
/home/travis/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jemoji (LoadError)
	from /home/travis/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /home/travis/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /home/travis/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
```

— https://travis-ci.org/dsernst/dsernst.github.io/builds/78518899

You can see on line 245 of that Travis log: `Installing jemoji 0.5.0`, so not sure where the problem is here. 

Any advice on how to get a more clear debug message?

Thanks

**Comment by parkr** [comment]
Change `jekyll build` to `bundle exec jekyll build` and give it another try.

**Comment by dsernst** [comment]
Thank you, Parker. That did the trick :smile:
