### ISSUE TITLE
<img> tags does not pass W3C validation

### ISSUE THREAD

**Issue by FiveYellowMice** [jekyll/jemoji#30]
It uses `align` attribute which is deprecated.

How about using `style` attribute instead?

**Comment by parkr** [comment]
I believe this is an issue with html pipeline, which is used to generate the html. Please file on jch/html-pipeline.

**Comment by moutons** [comment]
The issue with html-pipeline has been resolved, and one can now pass a hash to EmojiFilter like so:
`filter = EmojiFilter.new(body, {:asset_root => 'https://foo.com', img_attrs: Hash("draggable"=> false, "height" => nil, "width" => nil, "align" => nil)})`

Fixing this should be as simple as adding `img_attrs: Hash(align: nil)` to [the EmojiFilter hash](https://github.com/jekyll/jemoji/blob/8f00b113f80269dc856cc41c4a48a24b51c8e026/lib/jemoji.rb#L33)
