### ISSUE TITLE
The align attribute on the img element is obsolete.

### ISSUE THREAD

**Issue by adammacias** [jekyll/jemoji#31]
Can remove the attr `align`? [W3C](https://validator.w3.org) say is obsolete. 

![showing results for contents of text input area nu html checker](https://cloud.githubusercontent.com/assets/1139893/12724339/a65b3c54-c8f4-11e5-9c50-e82c0f04b749.png)

**Comment by parkr** [comment]
@adammacias Sure. We might need to specify it in a `style` attribute instead to preserve the look.

**Comment by adammacias** [comment]
yes @parkr, but this can add in stylesheet. `.emoji { align: absmiddle; }`.

a good idea could be:

```
emoji:
  src: "/assets/images/emoji"
  css_inline: false
```

**Comment by parkr** [comment]
Looking into it further, this actually requires a change to the `html-pipeline` gem. [They define it here](https://github.com/jch/html-pipeline/blob/1bfbd69649b728c56bfef2782d131424042ca435/lib/html/pipeline/emoji_filter.rb#L74).

**Comment by adammacias** [comment]
Okay, thank u. :smile:
