### ISSUE TITLE
jemoji no longer working for Jekyll 3.0+ releases

### ISSUE THREAD

**Issue by kvz** [jekyll/jemoji#32]
Both on our site, as on jekyllrb.com, this seems to be the case:

![](https://dl.dropboxusercontent.com/s/pmr1c67yripqm8h/2016-02-05%20at%2011.58.png?dl=0)

Our `_config.yml` has:

```yaml
gems:
  - jemoji
```

Our `Gemfile` has:

```yaml
gem 'jekyll', '3.0.1'
gem 'jemoji', '0.5.1'
```

I have also tried with jemoji 0.5.1 and jekyll 3.1.1, no luck.

**Comment by parkr** [comment]
@kvz It should work fine. Are you using `bundle exec jekyll serve` when testing out your site?

**Comment by kvz** [comment]
Yes indeed

**Comment by parkr** [comment]
@kvz I can't reproduce here or on GitHub Pages. Try upgrading to v3.0.2. Another plugin may be interfering with it, too. Sorry I can't be of more assistance! It doesn't look like a bug.

**Comment by kvz** [comment]
Hm ok. These are my other plugins and related config:

```
gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

emoji:
  src: "/img"
```

Anything suspicious?

**Comment by parkr** [comment]
@kvz Did you try 3.0.3? Also, upgrade jemoji to v0.5.1. Your config looks fine.

**Comment by kvz** [comment]
Tried those versions just now. I had to change these dependencies for it:

```bash
Bundler could not find compatible versions for gem "html-pipeline":
  In Gemfile:
    jemoji (= 0.5.1) ruby depends on
      html-pipeline (~> 2.2) ruby

    html-pipeline (= 1.11.0) ruby

Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    html-pipeline (= 2.2) ruby depends on
      nokogiri (<= 1.6.5, >= 1.4) ruby

    nokogiri (= 1.6.7.2) ruby
```

Which I did and it succeeded the build, but still no luck unfortunately:

![](https://dl.dropboxusercontent.com/s/u3r2y0l6zij1pij/2016-02-09%20at%2020.16%202x.png?dl=0)

**Comment by captn3m0** [comment]
@kvz It looks like this is fixed on the jekyllrb website. Any pointers on how you managed that? I'm running jekyll 3.1 locally and it works perfectly fine but doesn't render on github-pages (3.0).

**Comment by parkr** [comment]
@captn3m0 We added `jemoji` to `gems` array in `_config.yml` and ran `bundle exec jekyll serve -s site` and it all worked. 😄

**Comment by captn3m0** [comment]
I think I found the difference in how 3.0 and 3.1 handle emojis. I'm running some yaml holding markdown content through `markdownify` filter. Direct emojis in posts are getting converted fine, but the markdownify filter ignores emojis in 3.0, it seems.

I'll have to wait for github-pages to update to 3.1, I guess.

[markdownify-in-code](https://github.com/captn3m0/captn3m0.github.com/blob/45108a22bc18829be79c262579401e4f4fcdec74/pages/ama.md) vs [rendered version](https://captnemo.in/ama/). You can search for `:joy:` to see the shortcode rendered as it is. The yaml file is [available here](https://github.com/captn3m0/captn3m0.github.com/blob/master/_data/projects.yml)

**Comment by parkr** [comment]
> the markdownify filter ignores emojis in 3.0, it seems

This filter has nothing to do with `markdownify`. `markdownify` uses the markdown renderer (e.g. kramdown) to render the code as markdown. This plugin simply takes a document's full output (layout and all) after it's been rendered and replaces emoji.

I'm seeing the proper output here: https://captnemo.in/ama/
