### ISSUE TITLE
Emoji not working local (?)

### ISSUE THREAD

**Issue by GeekinaCave** [jekyll/jemoji#35]
Hi, i have a problem with jemoji; in github pages is working fine but when i try to build locally this happens (_config.dev.yml is a alternative configuration file which only difference is url: http://localhost:4000):

I:\GitHub\testingghp>bundle exec jekyll serve --config _config.dev.yml
Configuration file: _config.dev.yml
  Dependency Error: Yikes! It looks like you don't have jemoji or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jemoji' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.2 | Error:  jemoji

However i have jemoji and his dependencies installed:

*** LOCAL GEMS ***

activesupport (4.2.6)
addressable (2.4.0)
bigdecimal (1.2.4)
bundler (1.11.2)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colorator (0.1)
ethon (0.8.1)
execjs (2.6.0)
faraday (0.9.2)
ffi (1.9.10 x64-mingw32)
gemoji (2.1.0)
github-pages (56)
github-pages-health-check (1.1.0)
html-pipeline (2.3.0)
i18n (0.7.0)
io-console (0.4.3)
jekyll (3.1.2, 3.0.3)
jekyll-coffeescript (1.0.1)
jekyll-feed (0.4.0)
jekyll-gist (1.4.0)
jekyll-mentions (1.1.1)
jekyll-paginate (1.1.0)
jekyll-redirect-from (0.9.1)
jekyll-sass-converter (1.4.0, 1.3.0)
jekyll-seo-tag (1.3.2)
jekyll-sitemap (0.10.0)
jekyll-textile-converter (0.1.0)
jekyll-watch (1.3.1)
jemoji (0.6.1)
json (1.8.3, 1.8.1)
kramdown (1.10.0, 1.9.0)
liquid (3.0.6)
listen (3.0.6)
mercenary (0.3.5)
mini_portile2 (2.0.0)
minitest (5.8.4, 4.7.5)
multipart-post (2.0.0)
net-dns (0.8.0)
nokogiri (1.6.7.2 x64-mingw32)
octokit (4.3.0)
octopress (3.0.11)
octopress-deploy (1.3.0)
octopress-escape-code (2.1.1)
octopress-hooks (2.6.1)
psych (2.0.5)
public_suffix (1.5.3)
rake (10.1.0)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdiscount (2.1.8)
rdoc (4.1.0)
redcarpet (3.3.4, 3.3.3)
RedCloth (4.2.9)
rouge (1.10.1)
safe_yaml (1.0.4)
sass (3.4.21)
sawyer (0.7.0)
terminal-table (1.5.2)
test-unit (2.1.8.0)
thread_safe (0.3.5)
titlecase (0.1.1)
typhoeus (0.8.0)
tzinfo (1.2.2)
wdm (0.1.1)

I try using ruby 2.1.8 which is almost the same as 2.1.7 used in github pages but with a security pacth (i checked), but the problem is the same.

repo: https://github.com/GeekinaCave/testingghp

Hope you can help me.

**Comment by pathawks** [comment]
You need to either add **jemoji** to your `Gemfile`, or switch entirely to using the **github-pages** gem.
