### ISSUE TITLE
Big icons

### ISSUE THREAD

**Issue by sklosedr** [jekyll/jemoji#44]
Hi,
I use the jemoji gem but the generated page has huge Icons.

http://docs.next-level-help.org/p1_emoji.html

How can I get the smaller onces?

The configuration is here https://github.com/sklosedr/sklosedr.github.io

Best regards
Stefan

**Comment by parkr** [comment]
Have you checked your CSS? We should be shopping them at normal size like how you see on GitHub.com :octocat:
