### ISSUE TITLE
the same thing in html?

### ISSUE THREAD

**Issue by facelesspanda** [jekyll/jemoji#50]
Hi

I'm not asking for a new feature or whatever, the use-case is pretty limited so I just need some help and clarification.

If I have, say, a `index.html` file (with YAML front matter and a layout and stuff), how do I go about using emojis in it?
As I understand it, these are GitHub Emojis, so it's intended to use in markup, but how would I use them in html, in a manner that would be test-able locally too?

I don't know if I'm clear, let me know if you have trouble understanding my issue.

Thanks for reading.

**Comment by parkr** [comment]
Hey @facelesspanda!

This plugin is intended to work in `.html` pages as well. If you aren't able to transform `:+1:` into a thumbs up `<img>` tag, then we should take a look at your source and figure out what the limitation is. Be sure to include it in your `_config.yml`:

```yaml
gems:
- jemoji
```

Any file which is output as an HTML page should be transformed. Hope this helps!

**Comment by facelesspanda** [comment]
Ah indeed, my config file had
```
gems:
  -  jemoji
```

Getting rid of those extra leading spaces did the trick.

Thanks for the reminder.
