### ISSUE TITLE
Unable to use emoji from Unicode Version 7.0+

### ISSUE THREAD

**Issue by misha-abasov** [jekyll/jemoji#53]
While many emoji work, 🤖 , 🇹🇷 , 🙃 , some others don't get rendered. They just show up as their aliases, i.e. `:robot:, :tr:, :upside_down_face_:, etc.`. 

The only pattern I can see is that the ones that don't work have been released as part of Unicode version later than 6.1. Help please?

![screen shot 2016-11-25 at 1 42 28 pm](https://cloud.githubusercontent.com/assets/3189023/20635673/0bc93086-b315-11e6-8c5c-0daffb243731.png)

**Comment by haffmaestro** [comment]
Also experiencing this issue!

**Comment by mmartinson** [comment]
It looks like this is using Gemoji 2.0 from 2014. @parkr is there any reason I'm not seeing to not update this. You accepting PRs?

**Comment by parkr** [comment]
@mmartinson PR away!

**Comment by naftulikay** [comment]
I also am affected, I cannot even use `:nerd_face:` sadly.
