### ISSUE TITLE
Jemoji images

### ISSUE THREAD

**Issue by zuchie** [jekyll/jemoji#60]
Hi, where can I have a reference of all the jemoji images and codes? Thanks.

**Comment by HorlogeSkynet** [comment]
Is this what you were looking for ? https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by zuchie** [comment]
Hi @HorlogeSkynet, yup that's what I'm looking for. Thanks:)

**Comment by parkr** [comment]
I use http://emoji.muan.co/ personally, but they look quite similar 😄
