### ISSUE TITLE
HTML tag inconsistency

### ISSUE THREAD

**Issue by rafed123** [jekyll/jemoji#63]
The jemoji plugin is altering tag structure in the rendered HTML.

In my layout Im usiing a `<gcse:searchresults-only></gcse:searchresults-only>`  tag. Whenever in a md file I add a emoji (like :tongue:) then it becomes `<searchresults-only></searchresults-only>`.

If I remove the emoji, then it renders fine.

I also use the seo plugin. Sometimes the seo generated tags end with backslash.
`<meta property="og:title" content="Test" />`

Sometimes they end without the backslash. I think this is a jemoji issue.

**Comment by benbalter** [comment]
Please see https://github.com/jekyll/jemoji/issues/43.

**Comment by rafed123** [comment]
Thank you so much. #43 is a nice workaround. But shouldn't this still be considered a bug?
