### ISSUE TITLE
jemoji parsing of included html in markdown files

### ISSUE THREAD

**Issue by pshriwise** [jekyll/jemoji#68]
I have a markdown posts in which I include some raw html files. It seems that jemoji is parsing that html and trying to insert emojis where some property:value pairs are located. This is, not surprisingly, breaking jekyll when I try to serve the site.

Is there a way around this?

**Comment by DirtyF** [comment]
Could you post a link to the mentioned file?

**Comment by pshriwise** [comment]
[markdown file](https://uwmadison.box.com/shared/static/zvq0ei4kewlkakbqcq19gm004wxm48fb.md)

[included html file](https://uwmadison.box.com/shared/static/00uh93uxw5ue17xjeqop1w7k2fajcd16.html)

**Comment by pathawks** [comment]
Wow. That HTML file is over a megabyte and looks like it is mostly minified JavaScript.

Could you provide a minimal example that demonstrates the issue?

**Comment by pshriwise** [comment]
This is true. Sorry. I'll try to come up with a more straightforward example.

**Comment by pshriwise** [comment]
I ended up working around this by using iframes and created a simple liquid tag to make it easier to include these html files in my posts.

In case someone else stumbles upon this same problem, here's the new tag I created (src is the local file to be included):
```
class IFrameTag < Liquid::Tag
  def initialize(tag_name, arg, tokens)
    super # mandatory
    @source, @width, @height = arg.split
  end

  def render(context)
        <<-MARKUP.strip
    <iframe type="text/html" src="#{@source}" width="#{@width}" height="#{@height}" frameborder="0" />
    MARKUP
  end
end

# register the tag
Liquid::Template.register_tag('iframe', IFrameTag)
```
