### ISSUE TITLE
update from 0.9.0 to 0.10.0 breaks emojis

### ISSUE THREAD

**Issue by rriemann** [jekyll/jemoji#80]
I updated the gems of my Jamstack website and found out that 0.10.0 is the gem that breaks eventually the emojis.

Actual result:

The website contains `:bike:`

Expected result:

The website contains :bike: (as emoji)

Have a look here: https://github.com/rriemann/blog.riemann.cc/commit/7c3efdb4b3d7837855e10a0480296d3653745bba

The next commit reverts the jemoji update to make emojis working again.

Unfortunately, I cannot provide at the moment a minimal not-working example. I use a proprietary gem in my setup.

Edit:

https://5b444c09fdd72a6adce6dbfd--blog-riemann.netlify.com/digitalisation/2018/06/06/open-letter-call-for-a-collaborative-data-protection-faq/

The table in the link above (output of the linked commit) should have plenty country flag emojis.

**Comment by parkr** [comment]
Could it be https://github.com/jekyll/jemoji/pull/74 that broke it, perhaps?

**Comment by ashmaroli** [comment]
@parkr  Yeah, #74 is a culprit. Local tests show that the *bug could be* due the regex involved in https://github.com/jekyll/jemoji/blob/173a17bc9f8516d87ad3bbb889a083b31ed13f6e/lib/jemoji.rb#L84-L85
https://github.com/jekyll/jemoji/blob/173a17bc9f8516d87ad3bbb889a083b31ed13f6e/lib/jemoji.rb#L12

Debugging in progress.. Feedback welcome.

**Comment by ashmaroli** [comment]
The bug has been successfully isolated. Opening a pull request shortly..
