### ISSUE TITLE
why emoji not working in online

### ISSUE THREAD

**Issue by jhyejun** [jekyll/jemoji#81]
It worked fine locally but do not work online.

What should I do?

my homepage is here [my homepage](http://jhyejun.com/projects)

**Comment by ashmaroli** [comment]
@jhyejun This is an unexpected regression from `v0.9.0`.. It'll take some time till a patch is released and bundled into GitHub Pages. The workaround until then is to **stop using the `compress` layout..**

**Comment by parkr** [comment]
Pages is using the latest release.

**Comment by parkr** [comment]
Duplicate of #80.
