### ISSUE TITLE
My emoji on github.io cannot display inline

### ISSUE THREAD

**Issue by Echo-Ji** [jekyll/jemoji#88]
Hey guys, I try to use emoji in my blogs which built on github pages.  I add pulgins in my `_config.yml` as follows:

```yaml
gems: 
  - jemoji
```

I want to display emoji inline, but it came out between lines 😭 . Click [here](https://echo-ji.github.io/2018/12/09/%E4%BC%98%E9%9B%85%E5%9C%B0%E5%9C%A8vim%E4%B8%AD%E6%9F%A5%E6%89%BE/) to check. How to solve it?

Thanks.

**Comment by DirtyF** [comment]
Check your CSS, currently `.post-container img` is `display: block`.
