### ISSUE TITLE
Issues with displaying emojis, wrong url

### ISSUE THREAD

**Issue by psaintemarie** [jekyll/jemoji#89]
It looks like the base url for the github emojis has changed:

- it used to be https://assets-cdn.github.com
- now it's https://github.githubassets.com

Am I the only one seeing this issue ?

**Comment by ashmaroli** [comment]
:wave: @psaintemarie 
You're right. The URL has indeed changed.

**Comment by DirtyF** [comment]
Emoji are well displayed on Jekyll's website: , e.g. https://jekyllrb.com/news/2018/09/19/security-fixes-for-3-6-3-7-3-8/

**Comment by ashmaroli** [comment]
If you inspect the emoji graphic, you'll see that the URL has changed to `https://github.githubassets.com/`

**Comment by DirtyF** [comment]
@psaintemarie a fix has been applied in latest release, thanks for reporting.

**Comment by chrisfinazzo** [comment]
I encountered this as well, but even after upgrading the gem, content is still served from the old URL. I want to set up a CSP directive for images, but don't know how to specify both my own domain and an external site.

**Comment by ashmaroli** [comment]
> but even after upgrading the gem, content is still served from the old URL

Probably due to browser-cache..?
Does this issue occur in a production env? If yes, can you provide us the site's URL and repo url..?

**Comment by chrisfinazzo** [comment]
I tried both clearing/ignoring the cache on load, no change.

The site is located [here](https://chrisfinazzo.com) ([repo](https://github.com/chrisfinazzo/blog)). I haven't committed a new version of the `_headers` file yet (what Netlify uses to set HTTP responses), but here is my current setup:

    Content-Security-Policy: default-src 'self'; script-src 'unsafe-inline'; style-src 'self'; img-src data: https:; connect-src 'self'; frame-ancestors none

**Comment by ashmaroli** [comment]
@chrisfinazzo You've locked `jemoji` to `0.9.x` in your Gemfile. Relaxing the version constraint should allow updating to newer releases:
```diff
-  gem "jemoji", "~>0.9.0"
+  gem "jemoji", "~> 0.9"
```

**Comment by chrisfinazzo** [comment]
Tried that - even after upgrading, still borked.

![enough](https://media.giphy.com/media/bPCwGUF2sKjyE/giphy.gif)

**Comment by DirtyF** [comment]
It's working fine locally on my end:
![chrisfinazzo-jemoji](https://user-images.githubusercontent.com/103008/53991982-0df46e00-412c-11e9-8f17-ec68184dad1e.png)
